name: PAC File Tests

on:
  push:
    branches:
      - main

jobs:
  test-pac-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium
      
      - name: Run PAC file tests
        run: python .github/workflows/pac-file-tests.py
